### ISSUE TITLE
NW-7.52 compatibility issues

### ISSUE THREAD

**Issue by stockbal** [stockbal/abap-search-tools#10]
Due to several hard to fix compatibility issues, especially the non-existing CDS View `ARS_ADT_API_FILTER` which is only available starting from NW 7.52 a new branch should be created for NW 7.52

**Comment by stockbal** [comment]
Branch `nw-752` was created to solve compatibility issues

Using this branch instead of `master` should solve the following issues
#2 
#3 
#4 
#5 
#6 
#7 
#8 
#9

**Comment by christianguenter2** [comment]
great! Works like a charm. Closing the issues.
