### ISSUE TITLE
Sap netweaver 7.52 Sp04

### ISSUE THREAD

**Issue by JavierRodriguezPrieto** [stockbal/abap-search-tools#13]
Hello,

I'm testing the search tool in eclipse 2020-06 and is not working. Its appearing the following error:

![image](https://user-images.githubusercontent.com/54849683/94996811-9d7b3080-059e-11eb-8c25-3b36d6381b1b.png)

Any suggestions?

Thanks

**Comment by stockbal** [comment]
Hi @JavierRodriguezPrieto,

The Tab *ABAP Source Search* is not originating from my plugin, but from the SAP ADT Tools Plugin - see this [blog entry](https://blogs.sap.com/2014/01/23/abap-sourcecode-search) .

The search tab that you get from my plugin is the following one.  
![image](https://user-images.githubusercontent.com/35834861/95188532-d7ca1500-07cc-11eb-85e8-19027bb89414.png)

Regards,
Ludwig

**Comment by JavierRodriguezPrieto** [comment]
ups my mistake, apologies. Now is working.

Thank you so much!
